### ISSUE TITLE
Crash caused by Gregicality Mystical Agriculture Intergration and Architecture Craft

### ISSUE THREAD

**Issue by J-Em1122** [Gregicality/gregicality#430]
Here are the mods installed
![image](https://user-images.githubusercontent.com/81498797/112740924-be827400-8f78-11eb-9656-e65069619143.png)
Only occurs when the Mystical Agriculture intergration is enabled in the configs. Once off in the configs, the game doesnt crash.

The Client Crash Report

---- Minecraft Crash Report ----

WARNING: coremods are present:
  GTCELoadingPlugin (gregtech-1.12.2-1.13.0.681.jar)
  GACoreMod (Gregicality-1.12.2-0.21.5.1.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 3/28/21 3:44 AM
Description: 
CCL Has caught an exception whilst rendering an item.
  Item Class:     class com.elytradev.architecture.common.shape.ItemShape
  Registry Name:  architecturecraft:shape
  Metadata:       0
  NBT:            {Shape:0,BaseName:"minecraft:planks",BaseData:0}
  Model Class:    class net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper$1
  Model Location: architecturecraft:__custitem__#normal
You can turn off player messages in the CCL config file.
If you want CCL to attempt to recover the game next time, enable it in the CCL config.

java.lang.ClassCastException: net.minecraft.item.ItemAir cannot be cast to net.minecraft.item.ItemBlock
	at gregicadditions.integrations.mysticalagriculture.items.MysticalAgricultureItems.lambda$null$12(MysticalAgricultureItems.java:256)
	at gregicadditions.integrations.mysticalagriculture.items.MysticalAgricultureItems$$Lambda$978/96624052.func_186726_a(Unknown Source)
	at net.minecraft.client.renderer.color.ItemColors.func_186728_a(ItemColors.java:148)
	at com.elytradev.architecture.client.render.shape.ShapeRenderDispatch.renderItemStack(ShapeRenderDispatch.java:86)
	at com.elytradev.architecture.client.render.RenderingManager$CustomItemRenderOverrideList.handleItemState(RenderingManager.java:384)
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:248)
	at codechicken.lib.render.item.CCRenderItem.func_184393_a(CCRenderItem.java:393)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:334)
	at codechicken.lib.render.item.CCRenderItem.func_180450_b(CCRenderItem.java:323)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147051_a(GuiContainerCreative.java:922)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:758)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at gregicadditions.integrations.mysticalagriculture.items.MysticalAgricultureItems.lambda$null$12(MysticalAgricultureItems.java:256)
	at gregicadditions.integrations.mysticalagriculture.items.MysticalAgricultureItems$$Lambda$978/96624052.func_186726_a(Unknown Source)
	at net.minecraft.client.renderer.color.ItemColors.func_186728_a(ItemColors.java:148)
	at com.elytradev.architecture.client.render.shape.ShapeRenderDispatch.renderItemStack(ShapeRenderDispatch.java:86)
	at com.elytradev.architecture.client.render.RenderingManager$CustomItemRenderOverrideList.handleItemState(RenderingManager.java:384)
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:248)

-- Item being rendered --
Details:
	Item Type: com.elytradev.architecture.common.shape.ItemShape@d9a9c76
	Item Aux: 0
	Item NBT: {Shape:0,BaseName:"minecraft:planks",BaseData:0}
	Item Foil: false
Stacktrace:
	at codechicken.lib.render.item.CCRenderItem.handleCaughtException(CCRenderItem.java:188)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:343)
	at codechicken.lib.render.item.CCRenderItem.func_180450_b(CCRenderItem.java:323)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147051_a(GuiContainerCreative.java:922)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:758)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (354, 46). Absolute: (1061, 759)
	Screen size: Scaled: (534, 300). Absolute: (1600, 900). Scale factor of 3

**Comment by warjort** [comment]
The issue here appears to be that color handlers are getting registered against "ItemAir".

````
 CROPS.values().stream().distinct().forEach(block -> {
            Minecraft.getMinecraft().getBlockColors().registerBlockColorHandler((state, worldIn, pos, tintIndex) -> ((MaterialBlockCrop) (state.getBlock())).getMaterial().materialRGB, block);

// HERE! AFAICT, these blocks have no items so these handlers get registered against the air item.

            Minecraft.getMinecraft().getItemColors().registerItemColorHandler((stack, tintIndex) -> ((MaterialBlockCrop) (((ItemBlock) stack.getItem()).getBlock())).getMaterial().materialRGB, block);
        });
````

It's kind of stupid that the other mod is asking for the colour of air, but there you go.

It's also stupid that minecraft/forge doesn't throw an error when you attempt this kind of registration, but since this is 1.12, that is unlikely to ever get fixed.

**Comment by Zafaranec** [comment]
I have same problem, is there some progress about this bug, maybe some workaround? Because is sad to select between Gregicality Mystical Agriculture Intergration and Architecture Craft. Can I ask, on which site is exactly this bug, Gregicality or ArchitectureCraft?

**Comment by htmlcsjs** [comment]
gregicalitiys by the looks of it, MA compat is moving to another mod, gregification, when CEu comes out

**Comment by Zafaranec** [comment]
Gregification will be awesome, I'm watching development on Discord channel, but from it, it will maybe long time to completing sadly...
