### ISSUE TITLE
[Crash] Probably related to AnnotatedMaterialHandler?

### ISSUE THREAD

**Issue by alfuken** [Gregicality/gregicality#516]
Gregtech 1.15.1.735 (built from sources, commit f9d7017c6daa886b281cb355ce27a499b9e0e092)
Gregicality 0.22.4.1 (built from sources, commit a5cc9c1f6f63d7548554af18f8f33a741bb5bf6f)

Full log: https://pastebin.com/nRaZCpfs
Crash log: https://pastebin.com/f5QPdzPK

**Comment by alfuken** [comment]
Gregicality-1.12.2-0.22.4.1 , gregtech-1.12.2-1.15.1.735 , CodeChickenLib-1.12.2-3.2.3.358-universal , forge 2855 — freshly installed from Curse — also crashes.

**Comment by warjort** [comment]
This is new validation added in the latest GTCE.

https://github.com/Gregicality/gregicality/blob/a5cc9c1f6f63d7548554af18f8f33a741bb5bf6f/src/main/java/gregicadditions/GAMaterials.java#L36

duplicates:

https://github.com/GregTechCE/GregTech/blob/f9d7017c6daa886b281cb355ce27a499b9e0e092/src/main/java/gregtech/api/unification/material/type/DustMaterial.java#L66

**Comment by alfuken** [comment]
What would be a temporary solution? Downgrade GTCE until this is fixed on gregicality side?

**Comment by warjort** [comment]
1.15.0 doesn't have that validation.
But the validation was introduced so you don't get unexpected behaviour when this kind of conflict occurs.
If you are building from source, you should just be able to modify gregicality's value to be something unique.

**Comment by alfuken** [comment]
Adjusted them all by +1, seemed to help. But there has to be a better solution than this - some kind of auto-increment counter maybe?

Though now I'lm getting a load of other kind of exception:
```
[10:28:59] [Server thread/WARN] [gregtech]: There is no property with key explosives
[10:28:59] [Server thread/WARN] [gregtech]: Stacktrace:
java.lang.IllegalArgumentException: null
	at gregtech.api.recipes.recipeproperties.RecipePropertyStorage.getRecipePropertyValue(RecipePropertyStorage.java:192) ~[RecipePropertyStorage.class:?]
	at gregtech.api.recipes.recipeproperties.RecipePropertyStorage.getRecipeProperty(RecipePropertyStorage.java:149) ~[RecipePropertyStorage.class:?]
	at gregtech.api.recipes.Recipe.getProperty(Recipe.java:351) ~[Recipe.class:?]
	at gregicadditions.recipes.categories.handlers.ElectricImplosionHandler.lambda$buildElectricImplosionRecipes$4(ElectricImplosionHandler.java:59) ~[ElectricImplosionHandler.class:?]
```
about 300 of those, but I guess that's a whole different story...

**Comment by DStrand1** [comment]
Fixed as of latest release.
